### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Grissess/simula#28]
Hello, under what license is this project released under ? Thank-you.

**Comment by Grissess** [comment]
Ahh...I don't usually choose a license when putting a project up, because I rarely get code working, much less to the proof-of-concept level :)

On that note, I'm open to suggestion--did you have a license or use case in mind?

**Comment by JacobErnst98** [comment]
AGPL - Use of this source code in other open source projects

**Comment by Grissess** [comment]
Careful, there--not sure if you meant GPL over AGPL (Affero GPL), which is stronger in terms and not generally compatible (usually used for web services).

I'm leaning either toward GPL3 (if copyleft is desired) or MIT (otherwise); the usual recommendation is "GPL if novel, MIT if a replacement", and this turns out to be competing with NI's LabView. Of course, I'm still open to feedback in any case--just trying not to rush the decision.

In particular, please assume in any case that the code is under _one_ of those two, so feel free to at least use or modify this code; whether or not you must also keep yours openly licensed is exactly what's up for debate.

**Comment by JacobErnst98** [comment]
I'm always a big fan of copy left, thanks for clearing up what the ability to use and modify the code!

**Comment by Grissess** [comment]
The commit message isn't transcluded here, but in summary:
- Let's do GPLv3 for now.
- The code can be dual-licensed MIT later if there is a desire.
- The best way to express that desire is a comment on this issue.

Hopefully that helps someone out :)
